site_name: notes.tamim's space
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: blue
nav:
  - Home: index.md
  - Communication Skills:
      - Everyday Phrases: docs/communication skills/Everyday_Phrases.md
      - Mouth Yoga: docs/communication skills/Mouth Yoga.md
  - Computer Science:
      - Computer Fundamentals:
       - Unit-1: docs/computer Sci/Computer_Fundamentals/computer_Fundamentals_Unit-1.md
      - Office Automation Unit-1: docs/computer Sci/Computer_Fundamentals/office Automation.md
      - Problem solving using  C:
        - Unit-1: docs/computer Sci/C/Unit-1_C.md
        - Unit-2: docs/computer Sci/C/Unit-2C_.md

- English:
      - 
